"""Document bytes the simulator returns for scans."""

import base64


def make_pdf(lines: list[str]) -> bytes:
    """A valid single-page A4 PDF showing `lines` of text."""

    def escape(text: str) -> str:
        return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")

    text = ["BT", "/F1 18 Tf", "72 760 Td", "24 TL"]
    text += [f"({escape(line)}) Tj T*" for line in lines]
    text.append("ET")
    stream = "\n".join(text).encode("latin-1", errors="replace")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        b"<< /Length %d >>\nstream\n" % len(stream) + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % number + body + b"\nendobj\n"
    xref_at = len(out)
    out += b"xref\n0 %d\n0000000000 65535 f \n" % (len(objects) + 1)
    for offset in offsets:
        out += b"%010d 00000 n \n" % offset
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (
        len(objects) + 1,
        xref_at,
    )
    return bytes(out)


# A scanned page, 496 by 702: a heading and four lines of words on white. The words are real
# ("Invoice 42", "Total due 118.00") so that a client reading the text of a scan has some to read.
PAGE_JPEG = base64.b64decode(
    "/9j/4AAQSkZJRgABAQAASABIAAD/wAARCAK+AfADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcI"
    "CQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRol"
    "JicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ip"
    "qrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAA"
    "AAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLR"
    "ChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaX"
    "mJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9sAQwAMDAwMDAwU"
    "DAwUHRQUFB0nHR0dHScxJycnJycxOzExMTExMTs7Ozs7Ozs7R0dHR0dHU1NTU1NdXV1dXV1dXV1d/9sAQwEODw8YFhgo"
    "FhYoYUI2QmFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh/90ABAAf/9oADAMB"
    "AAIRAxEAPwD1SiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//0PVK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP//R9UooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9L1SiiigAooooAKKKKAPL/iVJJGthsY"
    "rky9Dj+7Wa/grUo9NGp29+Swi83aQy8bd2AcnmtD4mfdsPrL/wCyVSTS/Hd/YR25mAtpIwANyr8hHAO0Z6UAa3hHxO/9"
    "j3curyM62RT5zlm2vwAfXBFby+NNCkaBIpGd7hgqqF5GW2/NnpzXNXPh0+H/AAdfpK4kmm8suV6DDjAH0yad4G8P6Zca"
    "cuqXUXmTeadpJOF2HjA+tAEulQ2C+M7iSO8Z5i0uYjGQB6/NnHH0rop/GGhW1zNazzFHgyGyp6qcYHqa4vRP+SgXX+/N"
    "VTT7C21Dx3dQ3aCSNZZXKtyCQTjP40Ad/pfi/RdVuRaW7skrfdDrjd9DyK47xP4qmh1uKDT7l0igOydQMDcrHd1HPFUt"
    "fs7bT/GdktlGsKs0L7UGBnfjgDjtU3ja2t08R2QSNFEoUvgAbiXOSfXPvQB6M3iDSU0xdXebbbvkKSCCSCRgDrnism08"
    "ceH7uYQea0RY4BkXCn8ecfjiuL+IC7NQs9Ot0CwrHlEQBV3MxBwBx2FVtW07VdShiig0P7IYv4oxyRjoemfqaAPUtV8Q"
    "abo0sUV8zK03K4BPTisi88R6bqlhqdnp7s7w2srFwMLwpHB7815/4uF2LLSEvVKzLAVYN1yCBzXoVxoGmaNoN99ii2yG"
    "0kVnJJZvlPX8fSgDG+G7u9ldl2LYkXqc9qyvH0sia9ZhGIBiXocfxtWJ4Y8KjxBBNMbkweUwXAXdnIz6iq2u6CPD+qW9"
    "qJjPvCvkrtx8xGOp9KAPZtR8Q6Zpd5FYXbMJZgCoCkjDEgc/UVNq2s2OiwpPfsVV22jaM84zXnHjfjxTYE/3I/8A0Y1a"
    "vxJI/s21XuZifyU0AQ+PrwT6RYXdqzBJm3qeQSGXIrStfGuhWdpbWs0rO6xIHKqWAO0Zye/4ZrnPFn/IqaL/ANc4/wD0"
    "WK1pvDmjL4O+0LEvnC2E3m/xF9u7r6E8YoA9CtrmC7gS5tnEkbjKsOhpLm5gs4HubpxHHGMsx6CuE+HEsr6TPExJRJvl"
    "9sgEj/PrW54u0y51XRntbQjzA6uFJxux2yaAM8fEDw8ZfLLSgf39nH88/pVvxRJY3vhx5mufLgkKMJUXf/EMcAivLjdX"
    "OnWK6XrOlqYQchypjkPOeJACD6dOldVqMunS+AWOlh1hV1G1zllbeCRn6nNAHQaLf6do3haC6knaW3UsPM2EEkuf4ck9"
    "eKdL478PRhCJXfeM/KpO361yM3/JNof+uh/9GtSwaPpzeAWv2hU3BDP5mPmyJCBz6YHSgDs7vxp4ftUjfzzL5ihgIwSQ"
    "D69MfQ81qRa5ps2mNq8Um63QEsQDkY6gjrmvOPDekadc+Er68uIVebEu1yMldiAjB7c81U8OknwjrK9gAfzFAHq2lavZ"
    "azbNdWLFkVihyMcgA/1qtpXiHTNZmkgsWZmiGWypHfFc58OSP7Dm9rhv/QUrB+HJB1K9I6FB/wChUAS/D+SR9Vvg7FgF"
    "7nP8VdRd+OfD9rMYPMaUqcExrlfz4z+FcV4LaFLnVmuWKRCFt7DqFyckfhVXTGilW4h8P6P9qR+DLckPj9FC+vWgD1GL"
    "xJo82myarFNugiwH4O5SSAMr171wnhPxVNLqUlvqty8gnKpCCMjcWx2HFRfDmKOdr+CdFkjZY8qwBBwWxkGm/D+3t5dU"
    "vGljRzGAULAHad3UelAHf6v4o0jRZBDdyEy4zsQbmA9+w/E03SfFWj6zL9ntZCsuMhJBtJ+nUH86888L20Gs+KbubVEE"
    "rKHkCPyN24DkdDgHpTfGNrb6Pr9pc6WghdgsmxBgbg2AQBwM0Aej3fijR7G/bTrqUxyoMtlTtA27uv0q1pGtWWtwyT2O"
    "4pG+wlhjJwDx+deXa7ZRaj48+xTZ2StGGx1xsBNes6fpljpcRgsIhEjHcQMnJ6Z5zQBeooooAKKKKACiiigAooooAKKK"
    "KACiiigAooooAKKKKACiiigAooooA//T9UooooAKKKKACiiigDjPGHhy98QLaizeNPJL7vMJH3tuMYB9K6uzha3tIbdy"
    "C0caqcdMgYqxRQBj+INOm1XSJ9PtyqyShcF8gcMDzgE9vSq/hjSbjRdKWxumRnVmbKEkcn3A/lXQUUAcNp3hi/tPFE+t"
    "yPEYZGkIUFt3z9Mjbj9aXTfDN/Z+J7jWpXiMMpkIUE7vnPGRtA/Wu4ooA4bW/DF/qXiG11aB4lih8vcGLBvkYscAKR09"
    "6PFnhi91m5gvtPkRJYV24ckdDkEEA85ruaKAOD1Pwrfa1pVuL+df7Sg3ZkH3WBJIBwBjjHOKxz4W8W6k0dvq18BBEeoY"
    "k/UAAZPuTXqlFAHn/iTwhdamLKLTnjSO1j2fvWbJ6Y6Kc9Oa7PU7Z73TrmziIDzRPGpbpllIGfartFAHI+EdAvNAt54b"
    "x43Mrhh5ZJGAMc5Aqj4o8Lahrep297ayRKkSBSHLA5DE8YU+td5RQBxXi3wtNrrRXVlIsc8Q24fIBXORyAcEGucvPBni"
    "fVIUfUL2OSVDhVdm2he5yF65x2/GvWKKAOE1zwvf6lomn6bA8SyWiqrliwU4QLxhSevsKw5vB/iv7Iulx3yPacfKWYAd"
    "8Y2k4z0/lXq9FAGPoOjw6HpyWMTbzks7YxuY9T/QVD4j0Rde042e/wAt1YOjdQGGRz7EGt6igDyc+G/Gr2P9jPcRfZOB"
    "gkYwDkc7d2K6CXwlLH4XbQrSRTM7h2d8hS2QT0BPQYFdxRQBwr+F79vCMegCSLz1bcWy2z75brtz0PpVyHQLyPwkdBLx"
    "+eUZd2TsyXLdcZ6H0rrqKAOQ0TQLzTfD1xpM7xtLN5mCpJX51wMkgH9Kq+HvCtxp2mXum6i6MLsYzEScDBHcDmu5ooA8"
    "otPBvieyMlna3yRWsx+cqWyR0+7jrj3/ABrd8J+F77QLu4mupI3SRQq7CSeDnnIFd1RQB55ovg68s/7QjvpYzHeRGMGM"
    "kkZPXkDpWfp/hTxZYpLp0F5HDaytl2XknPBI+XIOPcfWvU6KAOF8JeGdR8P3Vw9y8TxTKAChbdlTxwVA6E96z9N8Ka7o"
    "+s/arG4j+zPIPMGfmaPdkggqecehr0qigDzjVvB+pR6q2seHZ1hkclmUnbgnrg4IIPoabpvg/VLjVF1XxHOsrIQwUHcS"
    "R0B4AAHoK9JooA4a48M38vi1deV4hArKdpLb/lTb0246+9dzRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFF"
    "FABRRRQAUUUUAf/U9UooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA/"
    "/9X1SiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//1vVKKKKACiii"
    "gAooooA4XUZpl8eadArsI2gYlQTgnEnUdKqp47uZLR7+PTHaCJ9sriQYX0/h561q3ul303jCx1WOPNtDCyu+RwSH4xnP"
    "cdqyLDQdWh8I3ulyQ4uZpCyJuXkHb3zjse9AG/B4mSbVrbTvIKx3kAmilLdcjOCuODwe9U08ZQHT7zU5YCsFvL5MRDZM"
    "rfkMcYPeqGq6Bqsui6W9gmL+xVVK7lHBXDck44I9aku/Ck8nhGHSIMC5iImIJ4MnO4Z/EgH2FAFqy8WXDX1vZatYNZ/a"
    "/wDUsW3Ak9AeB/kjis7S9ds9LsdTvpFlYR3JQK7hyzHoF+Vdo/Oj7D4i17VLCbVbVbSGxbeTuBLsCDwAT1wP15qk/hTV"
    "bjSdQtmjCSvd+fECy4cDI6gnGQe9AHR6d4ouJ75bHVLF7IyIZEYtuBABPPAxwDWf/wAJy+03osJDp4fZ5+4Z+u3H9fxq"
    "9ZN4n1S4KalCtlaeUyOuVZnYgjII5A5z/jXHweFdTt1+wNpUM8gfi6eRgm33VWB/r7UAeuGeEQfaS4EQXfu7bcZz+VeY"
    "22qanfeKbG7aR47S6L+VFkgGNAQGZemSea9ButMhu9LbSnYpG0YjynBAGOmc+nfNcPN4OvotXsTbXNzJbRAhpWkG6MAc"
    "BehAPTgUASa9aasGv9Vvr+SzhhH+ipE+AxGcAgdz+fPtXV+G7u6vtEtbq9/1rqcnpnBIB/EYNcXq+meJL7XHvJ7AXdrC"
    "xEETSoqYHRiN2eevP4+leg6bJeS2Ub6hALebkNGpDAYJA5GR0xQBeooooAKKKKACiiigAooooAKKKKACiiigAooooAKK"
    "KKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//1/VKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP//Q9UooooAKKKKACiiigAorOvdX"
    "0zTnWO+uEhZhkBjjIp9lqen6iCbGdJtvUKQSPqKAL1FFFABRRRQAUUUUAFFUbzU9PsHRL2dImk+6GOM4/wD11eoAKKqw"
    "X1ndSSRW0ySPEcOqsCVPTnHSrVABRVCbVdOt7pbKadFmYZCZ5xjPSprS9tb+EXFnIJYySAy9MigCzRRRQAUUUUAFFFFA"
    "BRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAF"
    "FFFAH//R9UooooAKKKKACiiigDzHxfJDF4m06S4gNzGIzmILuLcnjB61BpUNyNbudbsLE6fbR274WYeWhbHGfQZ5OOmK"
    "7a90P7ZrdprHnbfsoI2bc7s57546+laWo2SalYzWMjFVmUrkdRnvQB5fa+KdXjvrMNfLdrPKElRYtqLkgYV8DJwe361o"
    "x33irUrvVY7K7SKOylcLuRSSAWwoOOmB1NXV8F3hW0SfUty2ThoV8oBQAc84YEk4HOax9N0jUNR1LWxZ3jWYa5dHG3cH"
    "Vmb3GCPUUAPuPGd++i2LxssNxcyMkku3cFCEZYLg9cjse9JaeKdUEOoWxuftJhhMsNx5ew5GMgqQPXuK6Sbwdbf2ba2d"
    "pO0M9mxeObGTuJySR7kD6Yp6eG76W1u49R1GS4luk2ZIxGg45CA4zx7UAP8AC0uu3lsuo6tMjxzRjy0VQCMfxHAHJrq6"
    "5LU9OvrPw3FpunTS+fCERGiUhmI9cH5Qe5J4rp0SVbdYy37wKBuPPOOvvzQB454mmttZ1i/Ms6xrYw7IQzAbnU5YAd/4"
    "h+VdTJ4nb/hFrWeJwt3dYgDMcBXHDOxPAx1/EVpaV4O0yygdL9UvZXcuZHTB57YyadpXhKzsIpra6KXcDSeZGjxj92Tw"
    "eSTnIx6dKAOd8FLZWes6jZQTpIMII23A+ZtzuI559eK9Ork7Pwva6Zd3uoQsAZlPlBI8GLgg7cHnPtir/huG/h0pF1J5"
    "JJSzHMud+0n5cgk4OO2eKAOHgs7xvGWoPLOkjwRb2LRqdylVwoB+7gEDI6496bb6rq1p4St9VsmVPKnIlVI0VWQnHQLg"
    "c4HGOtdsmg7NZvdX87P2uIR7Nv3cBRnOeenoKjsPDcdpoMmhSy+asgcF9u3G7ocZPT60AYd14lvf7UvJ7Nw1lY2wcrgY"
    "eRx8uTjI69j2rn7Txdq0U1tczXYuVmfEsAiK7FJ7NtGfz/Ou20jwpbabpdzpk8hn+1ZDvjacYwAOT06iq1l4X1K2kghl"
    "1WVrS3OUiQbCQP4WYHJH+RigDe166nstHuru2bZLHGWU4BwfoeK4KTX/ABJYaEusXc0bm72xwqFHynklyAOSQOnTnp2r"
    "0TVLH+0tPnsN/l+cpXdjOM+2RWTc+GoLvQYdEmlOYAuyUDBDLwDjPv0zQByujeJtQXVFsZrpb+KWNiJDGYtjgE4OQvHH"
    "Wsw+LNZt5Ypzfx3JaXbJCkX7tRns5Azken512lv4c1F2lOr6nLch4mhCKNigMCuSAcE4PcVlHwPdvZxWMmpEw277ol8o"
    "YGSSc4YEnn14oAL7UPEVz4iv9K0y6SGOCJZBuRTj5VJAOCeSe9Yh8Q+KP7Gi183MflpL5Rj2DL+5OO/TjFd9FoJj1u71"
    "kzZN1EItm3G3AUZznn7vTFZP/CHf8U9/YP2r/lr5nmbP027v60AY2v8AiLVbbV2t/tJsLcRq0TeUJA5IB5PJxkkcA9Ol"
    "d1od1cXmlw3FzJHLIwOXiOVOCRnoMH1HrWHqHhm/mnklsdQMaTKFkjkQSJwMZUNwP881t6JpMWi6dHYRMX25JY8ZJOSc"
    "dqANaiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//"
    "0vVKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP//T9UooooAKKKKA"
    "CiiigAorC1bxJpeizJBfsys67htUnjOKTS/E2j6xMbeylJlAztZSpIHpnrQBvUVnaXqtnq9u1zZEsiuUORjkAH+taNAB"
    "RRWdbarZ3d5cWEDEy22BICCAM9MHvQBo0UVUgv7O5uJrWCQPLAQJFHVc9M0AW6KKKACiiigAooooAKKKKACiiigAoooo"
    "AKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigA"
    "ooooA//U9UooooAKKKKACiiigDzfxOL0+LNNGnbPtHlNs8zO3+LOce1VrUX9v41tn11Y/OliYRmDhejDkdT3HPtXX6x4"
    "ZstauY7u4lmikiXapiYLxnPdSaj0vwnpml3f29GlmnAIDzNuIzwcYA7UAcBpt49p4TkEdy1s0l6y5jBaRhtX5VwRg++a"
    "v6Lquo2OqXttI9y8MVq8yx3ZzICoBGfTPPFdQfBml/2eNPWSYBZjOsm4b1cgDggAY49KsWPhWxsb46gJp5pXQxyeawcO"
    "D13ZGfTv2oA5HTrbWb3TYfEP9sGGaSQ5WZ8Q4DEbcdO3TFY2qaveabrWrJZkxm4dFeZcny1HUjHc56/1ruovA2lRzKxl"
    "neBH8xYGfMYb6Yz/AF96028NadJJfySF2/tAASAkYGOhXjgjrzmgDS02BbexijWZ7gbQfNdixbPOcnse1eY6ek2l6jrl"
    "7FPLI9kuRubPmEhgC/rjrXpul6dHpVkljDI8iR52mQgkD0yAOB2rNHhqxGpzamHk/wBJBWWLd+7fIwcjGT+fWgDz+X+1"
    "7LQoPFK6nM80jgtGzZQgkjGOnHpWr/xMdc8TXNkl7PawG3jl2xseCUTgDtyecVrx+BNKSRd807wI29YGf5M/ln+vvW/B"
    "o1rBq02soz+dOgjZSRsAGOgxn+Ed6APNF8Q6xD4Vk/fs8/2v7OJTywXbu6+vHXrzV3TJtcs78xqL57SSJ95ulIKuFJDK"
    "cnHOO9ddH4S0pNOn0xvMkink80liNytwMqQBjpTLDwnY2c7XUs01zKUMatK24opGPl49DQBj+CYdTvLdNXvr6WVBvRYm"
    "JI69SSeTnpXoNc02gwWfh6bRrQSyqytgblDksc/eIAHPtWppFnJp+mW1lKQzxRhWI6Z70AeexLqfiKfU7xtQltRZsyxR"
    "xsVA25wWwR6daptrOr6lZ6KqXMkEs07wu6HG7BQAkDg4B/Ouxv8AwZp17dS3Uc01uZ/9asTAK/rkEHr+VXW8M6ZiwWPf"
    "GunsXjCkYJJBO7IJOSPagDlLa81HQ9Y1Kwa6ku4oLR7hPNO47gAR/M5xWBa3viN4YdVtGv57hnLMCubdlyeBg/0+nSvU"
    "v7CsjqsuruWaSaLyWQ42FeO2M9vWsWPwPpaSrumne3R9627PmMH6YoA7JTuUMRjIziloooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9X1SiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//1vVKKKKACiiigAooooAKK5TWPFP9"
    "j3EkUljPJHGATKo+TkDv074qbRfER1mby1sp4EKb1kkXCHkcA++aAOlopAykkAgkdazrTVrS9vLmxg3eZakCTIwOc9PX"
    "pQBpUUZGcZ5rGs9ZhvdUu9LSNle0xuY4wc+lAGzRQSAMngVjW2tQ3OsXOjLGwe2UMWOMHIB4/OgDZoopCQOpxmgBaKK5"
    "/VPE2l6VKlvI/mzO4QxxkFlz3bnigDoKKzNU1jT9Igaa9lVSFJVMjc2OyjvUS65Zf2MNcl3RwFN2CPm5OAMDuTQBsUVy"
    "+l+LLHU7tLHypreSVd8YlXAdeuRgnsK1tW1W00azN7eE7AQoCjJYnoBQBpUVz2k+JLLVZZbbZJbzQrvaOZdp2+vXpyKo"
    "QeNtKnuUhEcyxSP5aTsmIy31zn9PrigDsKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigA"
    "ooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP/1/VKKKKACiiigAooooA5jxn/AMi1efRf/Q1rG1G6ubPwFBLa"
    "EqxghUsOoDYB/wAK7e9srbULZ7O8TfFJjcuSM4Oeoweopq2NotkNO8sG3CCMIeRtAxjmgDye4srLQ/7Hv9FmZrmdlDgN"
    "neGxnI7DPGP61oaHZafYa1rM/wA0YsVJjIJJVSG3HBPPHrXY2PhTQdOuRd2tviReVLMzbfoCTVptA0hr99SaAGeQFWOT"
    "ghhtOVzjke1AHjUiNbwWmrWsUkRln+W4eXdJJgnPyjGACOa9D0L/AJG7Wf8AgFaQ8GeG1BH2Xqc/ffI+h3cVs2+mWNrd"
    "zX0Ee2afHmNuY5x04Jx+VAHE+J0XUPE2naPfOUs3QuQDgM3zcfoB+NYljbQWmoeILW0cyRx2ciqScnhRxn26fhXpmqaL"
    "pusoseoRCTYcqckEZ64IxUdj4f0fTXeSytxGZE8tuWIK+hBJH19aAPMNQuIT4AsYg4L+cRtzzwXJ4p+pxXOr+IdQinh+"
    "0i3XbGpmEQjXH3hnr6n9a7z/AIQvw183+iD5jn778fT5uKt6l4a0bVphcXsG6QDG4EqSB64IzQBV8INeHRI0vZFlaNmV"
    "WVxICo6fMpI46VheOLO0i+xXUcKLNJdKGcKAzcdz1Nd7a2tvZW6WtqgjijGFUdBVe/0yx1NY1vo/METh15Iww78EUAZf"
    "imztJ9Fup5oUeSKFyjMoJXjsT0rlrqaKH4dxCWPzBJGqAdMEtkH8MZr0a5toby3ktbhd0cilWGSMg+45qqNK0/8As/8A"
    "soxA2wXbsJJ469Sc9fegDzXTlurHxFpJ1Kdb3zINsRX/AJZgggdOvpk/0rY8ZXVtcQafcwypLAl2odkYMoOM8kcdK6TT"
    "fDGi6VP9psoNsvQMzFiM+mScVJH4d0aKwk0xLcfZ5G3shZj83AyCTkHgdDQBxer7p/FN4LQ7mXTpA23nkqcfzFY95JC/"
    "gLT4YiDKbggKOu7L/wCP616fpeg6Vo+/+z4Qhk4ZiSxI9MkniqkPhTQLe8F/FagSBtw5O0H1C5x/h2oA6IZxz1ooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooA//9D1SiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//0fVKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP//S9UooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9P1SiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//1PVKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKAP//V9UooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooA//9b1SiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gD//1/VKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP//Q9UooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9H1SiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//0vVKKKKACiiigAooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP//T9UooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooA//9T1SiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigD//1fVKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "P//W9UooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9f1SiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//0PVKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP//R9UooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9L1SiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigD//0/VKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKAP//U9UooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA/"
    "/9X1SiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigD//1vVKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAP//X9UooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9D1SiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooAKKKKACiiigAooooAKKKKACiiigD//0fVKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK"
    "KKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoo"
    "ooAKKKKACiiigAooooAKKKKAP//S9UooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiii"
    "gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKA"
    "CiiigAooooA//9k="
)
