import enum
import uuid
from datetime import datetime

from sqlalchemy import ForeignKey, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base, IdMixin, TimestampMixin, str_enum


class DevicePlatform(enum.StrEnum):
    IOS = "ios"
    ANDROID = "android"
    WEB = "web"


class PushProviderName(enum.StrEnum):
    APNS = "apns"
    FCM = "fcm"


class Device(Base, IdMixin, TimestampMixin):
    """One installation of a PrinterHub client (FRD §55.1 item 4)."""

    __tablename__ = "devices"
    __table_args__ = (UniqueConstraint("user_id", "installation_id"),)

    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    # Generated by the client on first launch and kept for the life of the install.
    installation_id: Mapped[str] = mapped_column(String(128))
    platform: Mapped[DevicePlatform] = mapped_column(str_enum(DevicePlatform))
    name: Mapped[str | None] = mapped_column(String(200))
    model: Mapped[str | None] = mapped_column(String(200))
    os_version: Mapped[str | None] = mapped_column(String(64))
    app_version: Mapped[str | None] = mapped_column(String(64))
    push_provider: Mapped[PushProviderName | None] = mapped_column(str_enum(PushProviderName))
    push_token: Mapped[str | None] = mapped_column(String(512))
    last_seen_at: Mapped[datetime] = mapped_column(server_default=func.now())
