"""catalogue fields on capability profiles

Revision ID: 7540a1be76a0
Revises: 9c935a40dd8b
Create Date: 2026-10-08 01:32:47.176384+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7540a1be76a0"
down_revision: str | None = "9c935a40dd8b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "capability_profiles",
        sa.Column(
            "category",
            sa.Enum(
                "office_multifunction",
                "office_printer",
                "home_multifunction",
                "home_printer",
                name="profilecategory",
                native_enum=False,
                length=32,
            ),
            server_default="office_multifunction",
            nullable=False,
        ),
    )
    op.add_column("capability_profiles", sa.Column("summary", sa.String(length=200), nullable=True))
    op.add_column(
        "capability_profiles",
        sa.Column("popularity", sa.Integer(), server_default=sa.text("0"), nullable=False),
    )
    op.add_column(
        "capability_profiles",
        sa.Column(
            "setup_tips",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("capability_profiles", "setup_tips")
    op.drop_column("capability_profiles", "popularity")
    op.drop_column("capability_profiles", "summary")
    op.drop_column("capability_profiles", "category")
    # ### end Alembic commands ###
