"""share a document with the workspace

Revision ID: c05426e2f609
Revises: 7540a1be76a0
Create Date: 2026-10-10 21:52:19.463651+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "c05426e2f609"
down_revision: str | None = "7540a1be76a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("shared", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "shared")
    # ### end Alembic commands ###
