"""presets documents

Revision ID: 694c938a19a9
Revises: 9985e12a3ace
Create Date: 2026-10-07 13:39:40.725072+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "694c938a19a9"
down_revision: str | None = "9985e12a3ace"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "upload",
                "printer_scan",
                "camera_scan",
                name="documentsource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "storage_mode",
            sa.Enum("local", "cloud", name="storagemode", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=500), nullable=True),
        sa.Column(
            "upload_status",
            sa.Enum(
                "not_applicable",
                "pending",
                "uploaded",
                name="uploadstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.Column("source_printer_id", sa.Uuid(), nullable=True),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_documents_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_documents_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_printer_id"],
            ["printers.id"],
            name=op.f("fk_documents_source_printer_id_printers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index(
        "ix_documents_organization_id_owner_id",
        "documents",
        ["organization_id", "owner_id"],
        unique=False,
    )
    op.create_index(
        "ix_documents_retention_expires_at", "documents", ["retention_expires_at"], unique=False
    )
    op.create_table(
        "presets",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "scope",
            sa.Enum("personal", "organization", name="presetscope", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("print", "scan", "copy", name="jobtype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("printer_id", sa.Uuid(), nullable=True),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_presets_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_presets_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["printer_id"],
            ["printers.id"],
            name=op.f("fk_presets_printer_id_printers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_presets")),
    )
    op.create_index(
        "ix_presets_organization_id_owner_user_id",
        "presets",
        ["organization_id", "owner_user_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_jobs_document_id_documents"),
        "jobs",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_jobs_output_document_id_documents"),
        "jobs",
        "documents",
        ["output_document_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_jobs_output_document_id_documents"), "jobs", type_="foreignkey")
    op.drop_constraint(op.f("fk_jobs_document_id_documents"), "jobs", type_="foreignkey")
    op.drop_index("ix_presets_organization_id_owner_user_id", table_name="presets")
    op.drop_table("presets")
    op.drop_index("ix_documents_retention_expires_at", table_name="documents")
    op.drop_index("ix_documents_organization_id_owner_id", table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
