"""printers connections capabilities

Revision ID: 43f098b855d7
Revises: 62d7a661f83c
Create Date: 2026-10-07 13:25:56.437405+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "43f098b855d7"
down_revision: str | None = "62d7a661f83c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capability_profiles",
        sa.Column("manufacturer", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("model_patterns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("optional_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capability_profiles")),
        sa.UniqueConstraint(
            "manufacturer",
            "display_name",
            name=op.f("uq_capability_profiles_manufacturer_display_name"),
        ),
    )
    op.create_index(
        op.f("ix_capability_profiles_manufacturer"),
        "capability_profiles",
        ["manufacturer"],
        unique=False,
    )
    op.create_table(
        "printers",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("friendly_name", sa.String(length=200), nullable=False),
        sa.Column("manufacturer", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("capabilities_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "online",
                "offline",
                "sleeping",
                "unreachable",
                "unknown",
                name="printerstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "auto_fallback_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_printers_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_printers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_printers")),
    )
    op.create_index(
        op.f("ix_printers_organization_id"), "printers", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_printers_organization_id_serial_number",
        "printers",
        ["organization_id", "serial_number"],
        unique=True,
        postgresql_where=sa.text("serial_number IS NOT NULL AND deleted_at IS NULL"),
    )
    op.create_table(
        "connections",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("printer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "ipp",
                "ipps",
                "airprint",
                "android_print",
                "mopria",
                "escl",
                "wifi_direct",
                "usb",
                "http",
                "snmp",
                "smb",
                "sftp",
                "gateway",
                "cloud_relay",
                name="connectiontype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("purposes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("encrypted_credentials", sa.LargeBinary(), nullable=True),
        sa.Column(
            "health",
            sa.Enum(
                "connected",
                "degraded",
                "unavailable",
                "auth_required",
                "config_required",
                "unknown",
                name="connectionhealth",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_latency_ms", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_connections_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["printer_id"],
            ["printers.id"],
            name=op.f("fk_connections_printer_id_printers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connections")),
    )
    op.create_index(op.f("ix_connections_printer_id"), "connections", ["printer_id"], unique=False)
    op.create_table(
        "pairing_tokens",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("printer_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_pairing_tokens_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_pairing_tokens_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["printer_id"],
            ["printers.id"],
            name=op.f("fk_pairing_tokens_printer_id_printers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pairing_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_pairing_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_pairing_tokens_printer_id"), "pairing_tokens", ["printer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pairing_tokens_printer_id"), table_name="pairing_tokens")
    op.drop_table("pairing_tokens")
    op.drop_index(op.f("ix_connections_printer_id"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(
        "uq_printers_organization_id_serial_number",
        table_name="printers",
        postgresql_where=sa.text("serial_number IS NOT NULL AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_printers_organization_id"), table_name="printers")
    op.drop_table("printers")
    op.drop_index(op.f("ix_capability_profiles_manufacturer"), table_name="capability_profiles")
    op.drop_table("capability_profiles")
    # ### end Alembic commands ###
